
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CI Workflow

    on:
      workflow_dispatch:
      pull_request:
        branches:
          - main
          - master
        types: [opened, reopened, labeled, unlabeled, synchronize, closed]
        paths:
          - 'iterating_api_endpoint/**'

    concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

    jobs:
        ci: # ci using environments from workspace 'iterating_api_endpoint'
          uses: tinybirdco/ci/.github/workflows/ci.yml@v4.1.0
          with:
            data_project_dir: iterating_api_endpoint
            tb_env: test
          secrets:
            tb_admin_token: ${{ secrets.ITERATING_API_ENDPOINT_TOKEN }}  # set the Workspace admin token in GitHub secrets
            tb_host: https://api.tinybird.co
