##################################################
###   Visit https://github.com/tinybirdco/ci   ###
###   for more details or custom CI/CD         ###
##################################################

name: Tinybird - CD Workflow

on:
  workflow_dispatch:
  push:
    paths:
      - 'iterate_dynamodb/**'
    branches:
      - main
jobs:
  cd:
    uses: tinybirdco/ci/.github/workflows/cd.yml@v4.1.0
    with:
      data_project_dir: ./iterate_dynamodb
    secrets:
      tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_ITERATIONS }}
      tb_host: https://api.us-east.aws.tinybird.co
