##################################################
###   Visit https://github.com/tinybirdco/ci   ###
###   for more details or custom CI/CD         ###
##################################################

name: Tinybird - CD Workflow

on:
  workflow_dispatch:
  push:
    paths:
      - 'iterate_snowflake/**'
    branches:
      - main
jobs:
  cd:
    uses: tinybirdco/ci/.github/workflows/cd.yml@v4.1.0
    with:
      data_project_dir: ./add_column_snowflake_ds
    secrets:
      tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN_ADD_COLUMN_SNOWFLAKE_DS }}
      tb_host: https://api.tinybird.co
