
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
        paths:
          - 'iterating_api_endpoint/**'
    jobs:
      cd:
        uses: tinybirdco/ci/.github/workflows/cd.yml@v4.1.0
        with:
          data_project_dir: iterating_api_endpoint
          tb_env: prod
        secrets:
          tb_admin_token: ${{ secrets.ITERATING_API_ENDPOINT_TOKEN_PROD }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://api.tinybird.co
